language: node_js
node_js:
  - "10.9.0"
install:
  - npm install
  - npm run bootstrap
script:
  - npm run test
  - echo "test if pull request is completed"
  - node scripts/rebuildClients.js
  - git status | grep -q "working tree clean"
