version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing dependencies
      - npm install
  pre_build:
    commands:
      - echo Installing dependencies
      - npm run bootstrap
  build:
    commands:
      - echo Executing unit tests
      - npm run test
